import Image from "next/image";
import { ArrowUpRight, Mail, MapPin, Users } from "lucide-react";
import { PageIntro, SiteFooter, SiteHeader } from "../components";

const contacts = [
  {name:"Mike Vu", role:"Chief Product Officer", email:"mike@mihato.tech"},
  {name:"Harris Mai", role:"Chief Executive Officer", email:"harris@mihato.tech"},
  {name:"Tobi Huynh", role:"Chief Technology Officer", email:"tobi@mihato.tech"},
];
export default function Contact(){return <main className="new-site inner-page v21-page contact-page"><SiteHeader/><PageIntro eyebrow="LIÊN HỆ" title="Một cuộc trao đổi rõ ràng có thể bắt đầu một dự án tốt." lead="Chia sẻ bài toán, sản phẩm hoặc quy trình bạn đang muốn cải tiến. Bạn có thể gửi email trực tiếp đến thành viên phù hợp của MiHaTo hoặc để lại thông tin dự án."/>
<section className="contact-visual"><Image src="/media/mihato-office-brand.png" alt="MiHaTo - không gian thương hiệu" fill sizes="100vw"/><div><p>LET’S BUILD SOMETHING USEFUL</p><h2>Từ một cuộc trao đổi rõ ràng đến một kế hoạch có thể triển khai.</h2></div></section><section className="v21-contact"><div className="v21-contact-info"><p className="section-index">KẾT NỐI TRỰC TIẾP</p><h2>Trao đổi với MiHaTo</h2><p>Nhấn vào email để mở ngay ứng dụng email trên thiết bị và tạo thư mới với người nhận đã được điền sẵn.</p><div className="v21-contact-people">{contacts.map(c=><a key={c.email} href={`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(c.email)}&su=${encodeURIComponent("Trao đổi dự án với MiHaTo")}`} target="_blank" rel="noreferrer"><Mail/><span><b>{c.name}</b><small>{c.role}</small><strong>{c.email}</strong></span><ArrowUpRight/></a>)}</div><div className="v21-address"><MapPin/><span><b>CÔNG TY CỔ PHẦN MIHATO</b><br/>31 Nơ Trang Long, P. Gia Định, TP. Hồ Chí Minh</span></div></div>
<form action="mailto:mike@mihato.tech" method="post" encType="text/plain"><div className="v21-form-title"><Users/><div><b>Thông tin dự án</b><p>Giúp chúng tôi hiểu nhanh nhu cầu của bạn.</p></div></div><label>Họ và tên<input name="name" required placeholder="Nguyễn Văn A"/></label><label>Email công việc<input name="email" type="email" required placeholder="name@company.com"/></label><label>Tổ chức<input name="organization" placeholder="Tên công ty / đơn vị"/></label><label>Bạn muốn trao đổi về<select name="interest"><option>Giải pháp y tế</option><option>Product Engineering</option><option>Chuyển đổi số & tích hợp</option><option>MiHaTo Academy</option><option>Hợp tác khác</option></select></label><label className="full">Nội dung<textarea name="message" rows={6} required placeholder="Mô tả ngắn bài toán, quy mô hoặc mục tiêu..."/></label><button type="submit">Gửi thông tin <ArrowUpRight/></button></form></section><SiteFooter/></main>}
