import Image from "next/image";
import { Mail } from "lucide-react";
import { PageIntro, SiteFooter, SiteHeader } from "../components";
const team=[
{name:'Harris Mai',role:'Chief Executive Officer',short:'CEO',email:'harris@mihato.tech',focus:'Company Strategy',intro:"Co-Founder & CEO với kinh nghiệm phát triển phần mềm, phụ trách tầm nhìn công ty, vận hành và quan hệ đối tác công nghệ y tế.",skills:['Company Strategy','AI & Full-stack Engineering','Investor & Partner Relations']},
{name:'Tobi Huynh',role:'Chief Technology Officer',short:'CTO',email:'tobi@mihato.tech',focus:'Technology Architecture',intro:"Co-Founder & CTO, định hình chiến lược công nghệ, kiến trúc hệ thống và chất lượng kỹ thuật của MiHaTo.",skills:['System Architecture','Cloud & Data Engineering','Engineering Leadership']},
{name:'Mike Vu',role:'Chief Product Officer',short:'CPO',email:'mike@mihato.tech',focus:'Product Strategy',intro:"Co-Founder & CPO, kết nối bài toán chăm sóc sức khỏe, cơ hội thị trường và định hướng sản phẩm dài hạn.",skills:['Product Strategy','Healthcare Product-Market Fit','Business Development']}
];
export default function Team(){return <main className="new-site inner-page"><SiteHeader/><PageIntro eyebrow="ĐỘI NGŨ" title="Con người đứng sau mỗi quyết định sản phẩm." lead="MiHaTo quy tụ tư duy chiến lược, công nghệ và sản phẩm để cùng giải quyết những bài toán có ý nghĩa cho chăm sóc sức khỏe."/><section className="team-visual-banner"><Image src="/media/development-team.png" alt="Đội ngũ công nghệ MiHaTo" fill sizes="100vw"/><div><p>STRATEGY · TECHNOLOGY · PRODUCT</p><h2>Ba góc nhìn, một định hướng sản phẩm thống nhất.</h2></div></section><section className="v20-team-grid">{team.map((p,i)=><article key={p.name}><div className="v20-team-top"><span>0{i+1}</span><b>{p.short}</b></div><p className="section-index">{p.role}</p><h2>{p.name}</h2><h3>{p.focus}</h3><p>{p.intro}</p><div className="v20-skill-list">{p.skills.map(x=><span key={x}>{x}</span>)}</div><a href={`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(p.email)}&su=${encodeURIComponent("Trao đổi với MiHaTo")}`} target="_blank" rel="noreferrer"><Mail size={16}/>{p.email}</a></article>)}</section><SiteFooter/></main>}
