import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Building2, GraduationCap, HeartPulse, Hospital, Layers3, Workflow, CheckCircle2 } from "lucide-react";
import { BriefButton, PageIntro, SiteFooter, SiteHeader } from "../components";

const cases=[
 {icon:Hospital,tag:"HEALTHCARE · HIS",title:"Chuyển đổi số HIS — Nhi Đồng 315",lead:"Hệ thống HIS cho mô hình chuỗi 200+ phòng khám nhi khoa.",image:"/media/mihato-healthcare-experience.png",body:"Bài toán không chỉ là số hóa một màn hình khám bệnh mà là tạo nền tảng vận hành thống nhất khi số lượng cơ sở tăng lên. MiHaTo tiếp cận theo hướng chuẩn hóa luồng nghiệp vụ, dữ liệu và kiến trúc có khả năng mở rộng theo chuỗi.",points:["200+ phòng khám trong case HIS","Kiến trúc multi-tenant","Đồng bộ vận hành toàn chuỗi","Mở rộng theo từng cơ sở"],slug:"projects"},
 {icon:Building2,tag:"ENTERPRISE · ERP",title:"ERP Tổng thể",lead:"Một nguồn dữ liệu chung cho các hoạt động quản trị doanh nghiệp.",image:"/media/healthcare-data-integration.png",body:"Giải pháp ERP được định hướng để giảm vận hành rời rạc: kết nối tài chính – kế toán, kinh doanh & CRM, nhân sự, văn phòng số, dashboard điều hành và quản trị hệ thống trong một kiến trúc thống nhất.",points:["Tài chính – Kế toán","Kinh doanh & CRM","HRM & chấm công","Dashboard & phân quyền"],slug:"projects"},
 {icon:HeartPulse,tag:"DIGITAL HEALTH",title:"TeleCare",lead:"Duy trì kết nối chăm sóc sau khi người bệnh rời cơ sở y tế.",image:"/media/telecare-store.png",body:"TeleCare tập trung vào trải nghiệm chăm sóc liên tục trên thiết bị di động: kế hoạch chăm sóc, theo dõi thông tin sức khỏe và kết nối với đội ngũ phụ trách trong một hành trình rõ ràng.",points:["Mobile-first","Kết nối bác sĩ – người bệnh","Theo dõi kế hoạch chăm sóc","Trải nghiệm liên tục"],slug:"telecare"},
 {icon:GraduationCap,tag:"EDUCATION · CAPABILITY",title:"MiHaTo Academy",lead:"Biến công nghệ, AI và automation thành năng lực thực hành của đội ngũ.",image:"/media/mihato-meeting-space.png",body:"Chương trình đi từ tư duy hệ thống đến xây web app, dữ liệu, workflow automation, tích hợp AI và triển khai. Mục tiêu là tạo ra năng lực có thể áp dụng vào công việc thay vì chỉ học lý thuyết.",points:["AI & Prompt Engineering","Vibe Coding / Web App","Automation với n8n","Triển khai & DevOps"],slug:"academy"}
];
export default function Projects(){return <main className="new-site inner-page v21-page projects-page"><SiteHeader/><PageIntro eyebrow="DỰ ÁN & CASE STUDIES" title="Những gì MiHaTo đang xây dựng và đưa vào vận hành." lead="Mỗi dự án bắt đầu từ một vấn đề cụ thể trong vận hành. Đây là cách MiHaTo biến những vấn đề đó thành sản phẩm, quy trình và hệ thống có thể dùng thật."/>
<section className="projects-visual"><Image src="/media/mihato-healthcare-experience.png" alt="Dự án và năng lực triển khai MiHaTo" fill sizes="100vw"/><div><p>REAL PROBLEMS · REAL SYSTEMS</p><h2>Không chỉ kể đã làm gì. Quan trọng hơn là hệ thống giải quyết việc gì và được dùng như thế nào.</h2></div></section>
<section className="v21-project-overview"><div><p className="section-index">NĂNG LỰC TRIỂN KHAI</p><h2>Từ một điểm nghẽn nhỏ đến một hệ thống vận hành hoàn chỉnh.</h2></div><p>MiHaTo kết hợp phân tích nghiệp vụ, product engineering, dữ liệu và triển khai để xây hệ thống có thể sử dụng thật, tiếp tục mở rộng và được bàn giao rõ ràng.</p></section>
<section className="v21-case-list">{cases.map((c,i)=>{const Icon=c.icon;return <article key={c.title} className="v21-case"><div className="v21-case-image"><Image src={c.image} alt={c.title} fill sizes="(max-width:900px) 100vw, 48vw"/><span>{String(i+1).padStart(2,'0')}</span></div><div className="v21-case-copy"><div className="v21-case-tag"><Icon/>{c.tag}</div><h2>{c.title}</h2><h3>{c.lead}</h3><p>{c.body}</p><div className="v21-case-points">{c.points.map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div><BriefButton slug={c.slug}>Xem Executive Brief</BriefButton></div></article>})}</section>
<section className="v21-delivery"><div><p className="section-index">TỪ Ý TƯỞNG ĐẾN VẬN HÀNH</p><h2>Làm sản phẩm không bắt đầu và kết thúc ở code.</h2></div><div className="v21-delivery-grid">{[[Workflow,"Khảo sát & nghiệp vụ","Làm rõ người dùng, quy trình, dữ liệu và điểm nghẽn trước khi chốt phạm vi."],[Layers3,"Kiến trúc & sản phẩm","Thiết kế trải nghiệm, mô hình dữ liệu, phân quyền và khả năng mở rộng."],[CheckCircle2,"Triển khai & kiểm chứng","Phát triển theo giai đoạn, kiểm thử, đào tạo và đưa hệ thống vào sử dụng."],[ArrowUpRight,"Cải tiến & mở rộng","Theo dõi phản hồi, đo lường và tiếp tục bổ sung module theo nhu cầu."]].map(([I,t,d]:any)=><article key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="v19-cta"><div><p>TRAO ĐỔI DỰ ÁN</p><h2>Bạn đang có một hệ thống<br/>cần được làm rõ?</h2></div><Link href="/contact">Liên hệ MiHaTo <ArrowUpRight/></Link></section><SiteFooter/></main>}
